//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceClient.TS_Service {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TelephoneNumber", Namespace="http://schemas.datacontract.org/2004/07/WCF_Service.Models")]
    [System.SerializableAttribute()]
    public partial class TelephoneNumber : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TS_Service.ITS")]
    public interface ITS {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITS/GetDict", ReplyAction="http://tempuri.org/ITS/GetDictResponse")]
        WebServiceClient.TS_Service.TelephoneNumber[] GetDict();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITS/GetDict", ReplyAction="http://tempuri.org/ITS/GetDictResponse")]
        System.Threading.Tasks.Task<WebServiceClient.TS_Service.TelephoneNumber[]> GetDictAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITS/AddDict", ReplyAction="http://tempuri.org/ITS/AddDictResponse")]
        WebServiceClient.TS_Service.TelephoneNumber AddDict(WebServiceClient.TS_Service.TelephoneNumber telephoneNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITS/AddDict", ReplyAction="http://tempuri.org/ITS/AddDictResponse")]
        System.Threading.Tasks.Task<WebServiceClient.TS_Service.TelephoneNumber> AddDictAsync(WebServiceClient.TS_Service.TelephoneNumber telephoneNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITS/UpdDict", ReplyAction="http://tempuri.org/ITS/UpdDictResponse")]
        WebServiceClient.TS_Service.TelephoneNumber UpdDict(WebServiceClient.TS_Service.TelephoneNumber telephoneNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITS/UpdDict", ReplyAction="http://tempuri.org/ITS/UpdDictResponse")]
        System.Threading.Tasks.Task<WebServiceClient.TS_Service.TelephoneNumber> UpdDictAsync(WebServiceClient.TS_Service.TelephoneNumber telephoneNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITS/DelDict", ReplyAction="http://tempuri.org/ITS/DelDictResponse")]
        WebServiceClient.TS_Service.TelephoneNumber DelDict(string jj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITS/DelDict", ReplyAction="http://tempuri.org/ITS/DelDictResponse")]
        System.Threading.Tasks.Task<WebServiceClient.TS_Service.TelephoneNumber> DelDictAsync(string jj);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITSChannel : WebServiceClient.TS_Service.ITS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TSClient : System.ServiceModel.ClientBase<WebServiceClient.TS_Service.ITS>, WebServiceClient.TS_Service.ITS {
        
        public TSClient() {
        }
        
        public TSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebServiceClient.TS_Service.TelephoneNumber[] GetDict() {
            return base.Channel.GetDict();
        }
        
        public System.Threading.Tasks.Task<WebServiceClient.TS_Service.TelephoneNumber[]> GetDictAsync() {
            return base.Channel.GetDictAsync();
        }
        
        public WebServiceClient.TS_Service.TelephoneNumber AddDict(WebServiceClient.TS_Service.TelephoneNumber telephoneNumber) {
            return base.Channel.AddDict(telephoneNumber);
        }
        
        public System.Threading.Tasks.Task<WebServiceClient.TS_Service.TelephoneNumber> AddDictAsync(WebServiceClient.TS_Service.TelephoneNumber telephoneNumber) {
            return base.Channel.AddDictAsync(telephoneNumber);
        }
        
        public WebServiceClient.TS_Service.TelephoneNumber UpdDict(WebServiceClient.TS_Service.TelephoneNumber telephoneNumber) {
            return base.Channel.UpdDict(telephoneNumber);
        }
        
        public System.Threading.Tasks.Task<WebServiceClient.TS_Service.TelephoneNumber> UpdDictAsync(WebServiceClient.TS_Service.TelephoneNumber telephoneNumber) {
            return base.Channel.UpdDictAsync(telephoneNumber);
        }
        
        public WebServiceClient.TS_Service.TelephoneNumber DelDict(string jj) {
            return base.Channel.DelDict(jj);
        }
        
        public System.Threading.Tasks.Task<WebServiceClient.TS_Service.TelephoneNumber> DelDictAsync(string jj) {
            return base.Channel.DelDictAsync(jj);
        }
    }
}
