//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LW7b_Client.TSService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TelephoneNumber", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class TelephoneNumber : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TSService.TSServiceSoap")]
    public interface TSServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetDictResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDict", ReplyAction="*")]
        LW7b_Client.TSService.GetDictResponse GetDict(LW7b_Client.TSService.GetDictRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDict", ReplyAction="*")]
        System.Threading.Tasks.Task<LW7b_Client.TSService.GetDictResponse> GetDictAsync(LW7b_Client.TSService.GetDictRequest request);
        
        // CODEGEN: Generating message contract since element name telephoneNumber from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddDict", ReplyAction="*")]
        LW7b_Client.TSService.AddDictResponse AddDict(LW7b_Client.TSService.AddDictRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddDict", ReplyAction="*")]
        System.Threading.Tasks.Task<LW7b_Client.TSService.AddDictResponse> AddDictAsync(LW7b_Client.TSService.AddDictRequest request);
        
        // CODEGEN: Generating message contract since element name telephoneNumber from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdDict", ReplyAction="*")]
        LW7b_Client.TSService.UpdDictResponse UpdDict(LW7b_Client.TSService.UpdDictRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdDict", ReplyAction="*")]
        System.Threading.Tasks.Task<LW7b_Client.TSService.UpdDictResponse> UpdDictAsync(LW7b_Client.TSService.UpdDictRequest request);
        
        // CODEGEN: Generating message contract since element name jj from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DelDict", ReplyAction="*")]
        LW7b_Client.TSService.DelDictResponse DelDict(LW7b_Client.TSService.DelDictRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DelDict", ReplyAction="*")]
        System.Threading.Tasks.Task<LW7b_Client.TSService.DelDictResponse> DelDictAsync(LW7b_Client.TSService.DelDictRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDictRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDict", Namespace="http://tempuri.org/", Order=0)]
        public LW7b_Client.TSService.GetDictRequestBody Body;
        
        public GetDictRequest() {
        }
        
        public GetDictRequest(LW7b_Client.TSService.GetDictRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetDictRequestBody {
        
        public GetDictRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDictResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDictResponse", Namespace="http://tempuri.org/", Order=0)]
        public LW7b_Client.TSService.GetDictResponseBody Body;
        
        public GetDictResponse() {
        }
        
        public GetDictResponse(LW7b_Client.TSService.GetDictResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDictResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public LW7b_Client.TSService.TelephoneNumber[] GetDictResult;
        
        public GetDictResponseBody() {
        }
        
        public GetDictResponseBody(LW7b_Client.TSService.TelephoneNumber[] GetDictResult) {
            this.GetDictResult = GetDictResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddDictRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddDict", Namespace="http://tempuri.org/", Order=0)]
        public LW7b_Client.TSService.AddDictRequestBody Body;
        
        public AddDictRequest() {
        }
        
        public AddDictRequest(LW7b_Client.TSService.AddDictRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddDictRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public LW7b_Client.TSService.TelephoneNumber telephoneNumber;
        
        public AddDictRequestBody() {
        }
        
        public AddDictRequestBody(LW7b_Client.TSService.TelephoneNumber telephoneNumber) {
            this.telephoneNumber = telephoneNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddDictResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddDictResponse", Namespace="http://tempuri.org/", Order=0)]
        public LW7b_Client.TSService.AddDictResponseBody Body;
        
        public AddDictResponse() {
        }
        
        public AddDictResponse(LW7b_Client.TSService.AddDictResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddDictResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public LW7b_Client.TSService.TelephoneNumber AddDictResult;
        
        public AddDictResponseBody() {
        }
        
        public AddDictResponseBody(LW7b_Client.TSService.TelephoneNumber AddDictResult) {
            this.AddDictResult = AddDictResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdDictRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdDict", Namespace="http://tempuri.org/", Order=0)]
        public LW7b_Client.TSService.UpdDictRequestBody Body;
        
        public UpdDictRequest() {
        }
        
        public UpdDictRequest(LW7b_Client.TSService.UpdDictRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdDictRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public LW7b_Client.TSService.TelephoneNumber telephoneNumber;
        
        public UpdDictRequestBody() {
        }
        
        public UpdDictRequestBody(LW7b_Client.TSService.TelephoneNumber telephoneNumber) {
            this.telephoneNumber = telephoneNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdDictResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdDictResponse", Namespace="http://tempuri.org/", Order=0)]
        public LW7b_Client.TSService.UpdDictResponseBody Body;
        
        public UpdDictResponse() {
        }
        
        public UpdDictResponse(LW7b_Client.TSService.UpdDictResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdDictResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public LW7b_Client.TSService.TelephoneNumber UpdDictResult;
        
        public UpdDictResponseBody() {
        }
        
        public UpdDictResponseBody(LW7b_Client.TSService.TelephoneNumber UpdDictResult) {
            this.UpdDictResult = UpdDictResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DelDictRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DelDict", Namespace="http://tempuri.org/", Order=0)]
        public LW7b_Client.TSService.DelDictRequestBody Body;
        
        public DelDictRequest() {
        }
        
        public DelDictRequest(LW7b_Client.TSService.DelDictRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DelDictRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string jj;
        
        public DelDictRequestBody() {
        }
        
        public DelDictRequestBody(string jj) {
            this.jj = jj;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DelDictResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DelDictResponse", Namespace="http://tempuri.org/", Order=0)]
        public LW7b_Client.TSService.DelDictResponseBody Body;
        
        public DelDictResponse() {
        }
        
        public DelDictResponse(LW7b_Client.TSService.DelDictResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DelDictResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public LW7b_Client.TSService.TelephoneNumber DelDictResult;
        
        public DelDictResponseBody() {
        }
        
        public DelDictResponseBody(LW7b_Client.TSService.TelephoneNumber DelDictResult) {
            this.DelDictResult = DelDictResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TSServiceSoapChannel : LW7b_Client.TSService.TSServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TSServiceSoapClient : System.ServiceModel.ClientBase<LW7b_Client.TSService.TSServiceSoap>, LW7b_Client.TSService.TSServiceSoap {
        
        public TSServiceSoapClient() {
        }
        
        public TSServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TSServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TSServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TSServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LW7b_Client.TSService.GetDictResponse LW7b_Client.TSService.TSServiceSoap.GetDict(LW7b_Client.TSService.GetDictRequest request) {
            return base.Channel.GetDict(request);
        }
        
        public LW7b_Client.TSService.TelephoneNumber[] GetDict() {
            LW7b_Client.TSService.GetDictRequest inValue = new LW7b_Client.TSService.GetDictRequest();
            inValue.Body = new LW7b_Client.TSService.GetDictRequestBody();
            LW7b_Client.TSService.GetDictResponse retVal = ((LW7b_Client.TSService.TSServiceSoap)(this)).GetDict(inValue);
            return retVal.Body.GetDictResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LW7b_Client.TSService.GetDictResponse> LW7b_Client.TSService.TSServiceSoap.GetDictAsync(LW7b_Client.TSService.GetDictRequest request) {
            return base.Channel.GetDictAsync(request);
        }
        
        public System.Threading.Tasks.Task<LW7b_Client.TSService.GetDictResponse> GetDictAsync() {
            LW7b_Client.TSService.GetDictRequest inValue = new LW7b_Client.TSService.GetDictRequest();
            inValue.Body = new LW7b_Client.TSService.GetDictRequestBody();
            return ((LW7b_Client.TSService.TSServiceSoap)(this)).GetDictAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LW7b_Client.TSService.AddDictResponse LW7b_Client.TSService.TSServiceSoap.AddDict(LW7b_Client.TSService.AddDictRequest request) {
            return base.Channel.AddDict(request);
        }
        
        public LW7b_Client.TSService.TelephoneNumber AddDict(LW7b_Client.TSService.TelephoneNumber telephoneNumber) {
            LW7b_Client.TSService.AddDictRequest inValue = new LW7b_Client.TSService.AddDictRequest();
            inValue.Body = new LW7b_Client.TSService.AddDictRequestBody();
            inValue.Body.telephoneNumber = telephoneNumber;
            LW7b_Client.TSService.AddDictResponse retVal = ((LW7b_Client.TSService.TSServiceSoap)(this)).AddDict(inValue);
            return retVal.Body.AddDictResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LW7b_Client.TSService.AddDictResponse> LW7b_Client.TSService.TSServiceSoap.AddDictAsync(LW7b_Client.TSService.AddDictRequest request) {
            return base.Channel.AddDictAsync(request);
        }
        
        public System.Threading.Tasks.Task<LW7b_Client.TSService.AddDictResponse> AddDictAsync(LW7b_Client.TSService.TelephoneNumber telephoneNumber) {
            LW7b_Client.TSService.AddDictRequest inValue = new LW7b_Client.TSService.AddDictRequest();
            inValue.Body = new LW7b_Client.TSService.AddDictRequestBody();
            inValue.Body.telephoneNumber = telephoneNumber;
            return ((LW7b_Client.TSService.TSServiceSoap)(this)).AddDictAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LW7b_Client.TSService.UpdDictResponse LW7b_Client.TSService.TSServiceSoap.UpdDict(LW7b_Client.TSService.UpdDictRequest request) {
            return base.Channel.UpdDict(request);
        }
        
        public LW7b_Client.TSService.TelephoneNumber UpdDict(LW7b_Client.TSService.TelephoneNumber telephoneNumber) {
            LW7b_Client.TSService.UpdDictRequest inValue = new LW7b_Client.TSService.UpdDictRequest();
            inValue.Body = new LW7b_Client.TSService.UpdDictRequestBody();
            inValue.Body.telephoneNumber = telephoneNumber;
            LW7b_Client.TSService.UpdDictResponse retVal = ((LW7b_Client.TSService.TSServiceSoap)(this)).UpdDict(inValue);
            return retVal.Body.UpdDictResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LW7b_Client.TSService.UpdDictResponse> LW7b_Client.TSService.TSServiceSoap.UpdDictAsync(LW7b_Client.TSService.UpdDictRequest request) {
            return base.Channel.UpdDictAsync(request);
        }
        
        public System.Threading.Tasks.Task<LW7b_Client.TSService.UpdDictResponse> UpdDictAsync(LW7b_Client.TSService.TelephoneNumber telephoneNumber) {
            LW7b_Client.TSService.UpdDictRequest inValue = new LW7b_Client.TSService.UpdDictRequest();
            inValue.Body = new LW7b_Client.TSService.UpdDictRequestBody();
            inValue.Body.telephoneNumber = telephoneNumber;
            return ((LW7b_Client.TSService.TSServiceSoap)(this)).UpdDictAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LW7b_Client.TSService.DelDictResponse LW7b_Client.TSService.TSServiceSoap.DelDict(LW7b_Client.TSService.DelDictRequest request) {
            return base.Channel.DelDict(request);
        }
        
        public LW7b_Client.TSService.TelephoneNumber DelDict(string jj) {
            LW7b_Client.TSService.DelDictRequest inValue = new LW7b_Client.TSService.DelDictRequest();
            inValue.Body = new LW7b_Client.TSService.DelDictRequestBody();
            inValue.Body.jj = jj;
            LW7b_Client.TSService.DelDictResponse retVal = ((LW7b_Client.TSService.TSServiceSoap)(this)).DelDict(inValue);
            return retVal.Body.DelDictResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LW7b_Client.TSService.DelDictResponse> LW7b_Client.TSService.TSServiceSoap.DelDictAsync(LW7b_Client.TSService.DelDictRequest request) {
            return base.Channel.DelDictAsync(request);
        }
        
        public System.Threading.Tasks.Task<LW7b_Client.TSService.DelDictResponse> DelDictAsync(string jj) {
            LW7b_Client.TSService.DelDictRequest inValue = new LW7b_Client.TSService.DelDictRequest();
            inValue.Body = new LW7b_Client.TSService.DelDictRequestBody();
            inValue.Body.jj = jj;
            return ((LW7b_Client.TSService.TSServiceSoap)(this)).DelDictAsync(inValue);
        }
    }
}
